import * as XLSX from 'xlsx';
import { getEmployees, getAttendance, getSalaries, getDashboardSummary } from './dataStore.js';
import { formatCurrency, formatDate } from './formatters.js';

export const generateExcelFile = () => {
  try {
    // Create a new workbook
    const workbook = XLSX.utils.book_new();

    // 1. Employees Sheet
    const employees = getEmployees();
    const employeesData = employees.map((emp) => ({
      'Employee ID': emp.id,
      'First Name': emp.first_name || '-',
      'Last Name': emp.last_name || '-',
      'Email': emp.email || '-',
      'Phone': emp.phone || '-',
      'Position': emp.position || '-',
      'Department': emp.department || '-',
      'Hire Date': emp.hire_date ? formatDate(emp.hire_date) : '-',
      'Status': emp.status || '-'
    }));
    const employeesSheet = XLSX.utils.json_to_sheet(employeesData);
    employeesSheet['!cols'] = [
      { wch: 12 }, { wch: 15 }, { wch: 15 }, { wch: 25 }, { wch: 15 },
      { wch: 15 }, { wch: 15 }, { wch: 15 }, { wch: 12 }
    ];
    XLSX.utils.book_append_sheet(workbook, employeesSheet, 'Employees');

    // 2. Attendance Sheet
    const attendance = getAttendance();
    const attendanceData = attendance.map((att) => ({
      'Employee ID': att.employee_id,
      'Date': formatDate(att.date),
      'Check In': att.check_in || '-',
      'Check Out': att.check_out || '-',
      'Status': att.status || '-',
      'Notes': att.notes || '-'
    }));
    const attendanceSheet = XLSX.utils.json_to_sheet(attendanceData);
    attendanceSheet['!cols'] = [
      { wch: 12 }, { wch: 15 }, { wch: 12 }, { wch: 12 }, { wch: 15 }, { wch: 25 }
    ];
    XLSX.utils.book_append_sheet(workbook, attendanceSheet, 'Attendance');

    // 3. Salary Sheet
    const salaries = getSalaries();
    const salaryData = salaries.map((sal) => ({
      'Employee ID': sal.employee_id,
      'Month': sal.month || '-',
      'Year': sal.year || '-',
      'Base Salary': sal.base_salary ? formatCurrency(sal.base_salary) : '-',
      'Bonus': sal.bonus ? formatCurrency(sal.bonus) : '₹0.00',
      'Deductions': sal.deductions ? formatCurrency(sal.deductions) : '₹0.00',
      'Net Salary': sal.net_salary ? formatCurrency(sal.net_salary) : '-',
      'Paid On': sal.paid_on ? formatDate(sal.paid_on) : 'Not Paid',
      'Remarks': sal.remarks || '-'
    }));
    const salarySheet = XLSX.utils.json_to_sheet(salaryData);
    salarySheet['!cols'] = [
      { wch: 12 }, { wch: 8 }, { wch: 8 }, { wch: 15 }, { wch: 15 },
      { wch: 15 }, { wch: 15 }, { wch: 15 }, { wch: 25 }
    ];
    XLSX.utils.book_append_sheet(workbook, salarySheet, 'Salary');

    // 4. Dashboard Summary Sheet
    const summary = getDashboardSummary();
    const summaryData = [
      ['DASHBOARD SUMMARY', ''],
      ['', ''],
      ['Metric', 'Value'],
      ['Total Employees', summary.totalEmployees],
      ['Active Employees', summary.activeEmployees],
      ['Today Present', summary.todayPresent],
      ['Monthly Payroll', formatCurrency(summary.totalPayroll)],
      ['Average Salary', formatCurrency(summary.avgSalary)],
      ['', ''],
      ['Generated Date', new Date().toLocaleString()],
      ['Generated By', 'ANVVI Properties HR System']
    ];
    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
    summarySheet['!cols'] = [
      { wch: 25 }, { wch: 20 }
    ];
    XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

    // Generate filename
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `ANVVI_HR_Database_${timestamp}.xlsx`;

    // Write the file
    XLSX.writeFile(workbook, filename);

    return { ok: true, message: 'Excel file downloaded successfully!' };
  } catch (error) {
    console.error('Error generating Excel file:', error);
    return { ok: false, message: 'Failed to generate Excel file: ' + error.message };
  }
};
