services:
  - type: static
    name: annvi-hr-system
    staticPublishPath: frontend/dist
    buildCommand: npm --prefix frontend install && npm --prefix frontend run build
    envVars:
      - key: NODE_ENV
        value: production
